### ISSUE TITLE
The aggregate function in the docs only returns Deezer results

### ISSUE THREAD

**Issue by miqwit** [tchapi/tuneefy2#1]
Hi.

In the doc, at this URL: https://data.tuneefy.com/v2/aggregate/track?q=karma+police&mode=lazy&aggressive=false&include=deeezer, spotify, groove, I expected results from deezer and spotify and groove, but the response only includes a Deezer link. Is it normal?

"links": {
          "deezer": [
            "http://www.deezer.com/track/138539981"
          ]
        },

Besides, it seems there is an additional "e" in dee[e]zer, and problematic spaces between the comas and the platform names: include=dee[e]zer,[ ]spotify,[ ]groove.

Thanks.

**Comment by tchapi** [comment]
Hello @miqwit  !
You are right, there is a typo in the sample call: an extra "e" and unwanted spaces. I'll change that asap.

As for the results, it's just an example. When a platform does not have a specific catalog or does not respond correctly, we can't return the link even though it was included in the query.
